#!/bin/bash
#check if program is up to date

cd ~/hello/hello/hello
if git remote show origin | grep "local out of date"
then 
	echo "out of date"
	git pull origin
	cd ~/hello
	erlc ~/hello/hello/hello/hello.erl
	while read line
	do
		if scp -o ConnectTimeout=5 hello.beam $line:~/hello |& grep "lost connection"
		then
			echo $line >> ~/hello/needupdate.txt
		fi
	done < ~/hello/clients.txt
else
	echo "up to date"
	cd ~/hello
	if [ -s ~/hello/needupdate.txt ]
	then
		echo "needupdate.txt olemassa"
		sort ~/hello/needupdate.txt | uniq > ~/hello/temp.txt
		echo "needupdate -> temp"
		rm ~/hello/needupdate.txt
		while read line 
		do
			echo $line
			if scp -o ConnectTimeout=5 hello.beam $line:~/hello |& grep "lost connection"
			then
				echo "adding $line to needupdate"
				echo $line >> ~/hello/needupdate.txt
			fi
		done < ~/hello/temp.txt
		rm ~/hello/temp.txt
		echo "deleting temp.txt"
	fi
fi
